### ISSUE TITLE
Can't run Swift version in xCode 11.1

### ISSUE THREAD

**Issue by kseniya-hydric** [Firekast-io/firekast-demo-ios#2]
When trying to build Swift demo in latest xCode (11.1) I get an error:

Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: firekast-demo-ios-master/Pods/Firekast/Firekast.framework/Modules/Firekast.swiftmodule/arm64.swiftmodule

**Comment by francoisrouault** [comment]
Hi,

We just released SDK 1.7.2 which brings compatibility with Swift 5.1.

Please update versions in your Podfile:
```
pod 'Firekast', :podspec => 'http://firekast.io/sdk/ios/v1.7.2/Firekast.podspec'
pod 'VideoCore', :git => 'https://github.com/Firekast-io/VideoCore.git', :tag => 'fk-1.7.2'
```

Regards
