### ISSUE TITLE
Getting Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2

### ISSUE THREAD

**Issue by doobertAtGio** [Firekast-io/firekast-demo-ios#3]
I update my xCode to 11.2.1 last week and started to get the error indicated in the header. Is there a way to fix this? thanks!

**Comment by francoisrouault** [comment]
We have just released SDK 1.7.3 which brings support for Swift 5.1.2. 

To update Firekast, update your Podfile with:
```
  pod 'Firekast', :podspec => 'http://firekast.io/sdk/ios/v1.7.3/Firekast.podspec'
  pod 'VideoCore', :git => 'https://github.com/Firekast-io/VideoCore.git', :tag => 'fk-1.7.3'
```
Then run `pod update`.

Thank you for you support! :)
